name: stockflow
description: "StockFlow — Inventory & weekly ordering system."
publish_to: 'none'
version: 1.5.1+8

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  fl_chart: ^0.69.0
  pdf: ^3.11.0
  web: ^1.1.0
  supabase: ^2.5.0
  excel: ^4.0.0
  http: ^1.2.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/food_icon_brain.json

  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-400.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-500.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-600.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-700.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-800.ttf
          weight: 800
